(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    robot0 robot1 robot2 - robot
    printer0 printer1 printer2 printer3 - printer
)
(:init
    (robot_at robot0 wp0)
    (robot_at robot1 wp0)
    (robot_at robot2 wp0)

    (undocked robot0)
    (undocked robot1)
    (undocked robot2)


    (localised robot0)
    (localised robot1)
    (localised robot2)

    (dock_at wp0)


    (nocarrying_papers robot0)
    (nocarrying_papers robot1)
    (nocarrying_papers robot2)



    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 28)
    (= (distance wp1 wp0) 28)
    (= (distance wp0 wp2) 62)
    (= (distance wp2 wp0) 62)
    (= (distance wp0 wp3) 28)
    (= (distance wp3 wp0) 28)
    (= (distance wp0 printer0) 26)
    (= (distance printer0 wp0) 26)
    (= (distance wp0 printer1) 32)
    (= (distance printer1 wp0) 32)
    (= (distance wp0 printer2) 6)
    (= (distance printer2 wp0) 6)
    (= (distance wp0 printer3) 57)
    (= (distance printer3 wp0) 57)
    (= (distance wp1 wp2) 34)
    (= (distance wp2 wp1) 34)
    (= (distance wp1 wp3) 56)
    (= (distance wp3 wp1) 56)
    (= (distance wp1 printer0) 54)
    (= (distance printer0 wp1) 54)
    (= (distance wp1 printer1) 22)
    (= (distance printer1 wp1) 22)
    (= (distance wp1 printer2) 24)
    (= (distance printer2 wp1) 24)
    (= (distance wp1 printer3) 67)
    (= (distance printer3 wp1) 67)
    (= (distance wp2 wp3) 90)
    (= (distance wp3 wp2) 90)
    (= (distance wp2 printer0) 88)
    (= (distance printer0 wp2) 88)
    (= (distance wp2 printer1) 30)
    (= (distance printer1 wp2) 30)
    (= (distance wp2 printer2) 58)
    (= (distance printer2 wp2) 58)
    (= (distance wp2 printer3) 71)
    (= (distance printer3 wp2) 71)
    (= (distance wp3 printer0) 22)
    (= (distance printer0 wp3) 22)
    (= (distance wp3 printer1) 60)
    (= (distance printer1 wp3) 60)
    (= (distance wp3 printer2) 32)
    (= (distance printer2 wp3) 32)
    (= (distance wp3 printer3) 85)
    (= (distance printer3 wp3) 85)
    (= (distance printer0 printer1) 58)
    (= (distance printer1 printer0) 58)
    (= (distance printer0 printer2) 30)
    (= (distance printer2 printer0) 30)
    (= (distance printer0 printer3) 83)
    (= (distance printer3 printer0) 83)
    (= (distance printer1 printer2) 28)
    (= (distance printer2 printer1) 28)
    (= (distance printer1 printer3) 45)
    (= (distance printer3 printer1) 45)
    (= (distance printer2 printer3) 57)
    (= (distance printer3 printer2) 57)

)
(:goal (and
    (papers_delivered wp0)
    (papers_delivered wp3)
    (papers_delivered wp2)
    (papers_delivered wp1)
    (papers_delivered wp0)
    (papers_delivered wp3)
    (papers_delivered wp2)
))
)
