(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 printer3 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 69)
    (= (distance wp1 wp0) 69)
    (= (distance wp0 wp2) 85)
    (= (distance wp2 wp0) 85)
    (= (distance wp0 wp3) 27)
    (= (distance wp3 wp0) 27)
    (= (distance wp0 printer0) 32)
    (= (distance printer0 wp0) 32)
    (= (distance wp0 printer1) 64)
    (= (distance printer1 wp0) 64)
    (= (distance wp0 printer2) 27)
    (= (distance printer2 wp0) 27)
    (= (distance wp0 printer3) 39)
    (= (distance printer3 wp0) 39)
    (= (distance wp1 wp2) 64)
    (= (distance wp2 wp1) 64)
    (= (distance wp1 wp3) 88)
    (= (distance wp3 wp1) 88)
    (= (distance wp1 printer0) 85)
    (= (distance printer0 wp1) 85)
    (= (distance wp1 printer1) 53)
    (= (distance printer1 wp1) 53)
    (= (distance wp1 printer2) 80)
    (= (distance printer2 wp1) 80)
    (= (distance wp1 printer3) 92)
    (= (distance printer3 wp1) 92)
    (= (distance wp2 wp3) 112)
    (= (distance wp3 wp2) 112)
    (= (distance wp2 printer0) 117)
    (= (distance printer0 wp2) 117)
    (= (distance wp2 printer1) 21)
    (= (distance printer1 wp2) 21)
    (= (distance wp2 printer2) 112)
    (= (distance printer2 wp2) 112)
    (= (distance wp2 printer3) 124)
    (= (distance printer3 wp2) 124)
    (= (distance wp3 printer0) 29)
    (= (distance printer0 wp3) 29)
    (= (distance wp3 printer1) 91)
    (= (distance printer1 wp3) 91)
    (= (distance wp3 printer2) 30)
    (= (distance printer2 wp3) 30)
    (= (distance wp3 printer3) 54)
    (= (distance printer3 wp3) 54)
    (= (distance printer0 printer1) 96)
    (= (distance printer1 printer0) 96)
    (= (distance printer0 printer2) 5)
    (= (distance printer2 printer0) 5)
    (= (distance printer0 printer3) 25)
    (= (distance printer3 printer0) 25)
    (= (distance printer1 printer2) 91)
    (= (distance printer2 printer1) 91)
    (= (distance printer1 printer3) 103)
    (= (distance printer3 printer1) 103)
    (= (distance printer2 printer3) 24)
    (= (distance printer3 printer2) 24)
)
(:goal (and
    (papers_delivered wp1)
    (papers_delivered wp2)
    (papers_delivered wp1)
    (papers_delivered wp3)
    (papers_delivered wp0)
    (papers_delivered wp2)
    (papers_delivered wp2)
    (papers_delivered wp2)
    (papers_delivered wp0)
    (papers_delivered wp0)
))
)
