(define (problem reach)
  (:domain example)
  (:objects s1 s2 - sample)
  (:init
    (= distance 0)
    (transmissionavailable)
   ;; (at 5 (transmissionavailable))
    (at 45 (not (transmissionavailable)))
  )
  (:goal (and (>= distance 100)
              (<= distance 150)
              (transmitted s1)
              (transmitted s2))
  )
)