(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 printer3 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 36)
    (= (distance wp1 wp0) 36)
    (= (distance wp0 wp2) 32)
    (= (distance wp2 wp0) 32)
    (= (distance wp0 wp3) 56)
    (= (distance wp3 wp0) 56)
    (= (distance wp0 printer0) 65)
    (= (distance printer0 wp0) 65)
    (= (distance wp0 printer1) 37)
    (= (distance printer1 wp0) 37)
    (= (distance wp0 printer2) 29)
    (= (distance printer2 wp0) 29)
    (= (distance wp0 printer3) 89)
    (= (distance printer3 wp0) 89)
    (= (distance wp1 wp2) 14)
    (= (distance wp2 wp1) 14)
    (= (distance wp1 wp3) 30)
    (= (distance wp3 wp1) 30)
    (= (distance wp1 printer0) 29)
    (= (distance printer0 wp1) 29)
    (= (distance wp1 printer1) 73)
    (= (distance printer1 wp1) 73)
    (= (distance wp1 printer2) 57)
    (= (distance printer2 wp1) 57)
    (= (distance wp1 printer3) 125)
    (= (distance printer3 wp1) 125)
    (= (distance wp2 wp3) 24)
    (= (distance wp3 wp2) 24)
    (= (distance wp2 printer0) 43)
    (= (distance printer0 wp2) 43)
    (= (distance wp2 printer1) 59)
    (= (distance printer1 wp2) 59)
    (= (distance wp2 printer2) 43)
    (= (distance printer2 wp2) 43)
    (= (distance wp2 printer3) 111)
    (= (distance printer3 wp2) 111)
    (= (distance wp3 printer0) 59)
    (= (distance printer0 wp3) 59)
    (= (distance wp3 printer1) 59)
    (= (distance printer1 wp3) 59)
    (= (distance wp3 printer2) 27)
    (= (distance printer2 wp3) 27)
    (= (distance wp3 printer3) 95)
    (= (distance printer3 wp3) 95)
    (= (distance printer0 printer1) 102)
    (= (distance printer1 printer0) 102)
    (= (distance printer0 printer2) 86)
    (= (distance printer2 printer0) 86)
    (= (distance printer0 printer3) 154)
    (= (distance printer3 printer0) 154)
    (= (distance printer1 printer2) 32)
    (= (distance printer2 printer1) 32)
    (= (distance printer1 printer3) 76)
    (= (distance printer3 printer1) 76)
    (= (distance printer2 printer3) 68)
    (= (distance printer3 printer2) 68)
)
(:goal (and
    (papers_delivered wp3)
    (papers_delivered wp1)
    (papers_delivered wp2)
    (papers_delivered wp3)
    (papers_delivered wp2)
    (papers_delivered wp2)
))
)
