(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp3)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp1)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp2)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0) (at 500.003 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 500.003 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 500.003 (not (delivery_destination wp2)))
    (delivery_destination wp3) (at 500.003 (not (delivery_destination wp3)))

    (= (distance wp0 wp1) 11)
    (= (distance wp1 wp0) 11)
    (= (distance wp0 wp2) 5)
    (= (distance wp2 wp0) 5)
    (= (distance wp0 wp3) 5)
    (= (distance wp3 wp0) 5)
    (= (distance wp0 printer0) 8)
    (= (distance printer0 wp0) 8)
    (= (distance wp0 printer1) 5)
    (= (distance printer1 wp0) 5)
    (= (distance wp1 wp2) 8)
    (= (distance wp2 wp1) 8)
    (= (distance wp1 wp3) 12)
    (= (distance wp3 wp1) 12)
    (= (distance wp1 printer0) 3)
    (= (distance printer0 wp1) 3)
    (= (distance wp1 printer1) 6)
    (= (distance printer1 wp1) 6)
    (= (distance wp2 wp3) 10)
    (= (distance wp3 wp2) 10)
    (= (distance wp2 printer0) 5)
    (= (distance printer0 wp2) 5)
    (= (distance wp2 printer1) 4)
    (= (distance printer1 wp2) 4)
    (= (distance wp3 printer0) 13)
    (= (distance printer0 wp3) 13)
    (= (distance wp3 printer1) 6)
    (= (distance printer1 wp3) 6)
    (= (distance printer0 printer1) 7)
    (= (distance printer1 printer0) 7)
)
(:goal (and
    (papers_delivered wp3)
    (papers_delivered wp1)
))
)
