(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 - printer
    robot0 robot1 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp1)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (dock_at wp0)

    (delivery_destination wp0) (at 1230.004 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 1230.004 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 1230.004 (not (delivery_destination wp2)))
    (delivery_destination wp3) (at 1230.004 (not (delivery_destination wp3)))

    (= (distance wp0 wp1) 13)
    (= (distance wp1 wp0) 13)
    (= (distance wp0 wp2) 7)
    (= (distance wp2 wp0) 7)
    (= (distance wp0 wp3) 8)
    (= (distance wp3 wp0) 8)
    (= (distance wp0 printer0) 19)
    (= (distance printer0 wp0) 19)
    (= (distance wp0 printer1) 26)
    (= (distance printer1 wp0) 26)
    (= (distance wp0 printer2) 18)
    (= (distance printer2 wp0) 18)
    (= (distance wp1 wp2) 8)
    (= (distance wp2 wp1) 8)
    (= (distance wp1 wp3) 15)
    (= (distance wp3 wp1) 15)
    (= (distance wp1 printer0) 6)
    (= (distance printer0 wp1) 6)
    (= (distance wp1 printer1) 15)
    (= (distance printer1 wp1) 15)
    (= (distance wp1 printer2) 7)
    (= (distance printer2 wp1) 7)
    (= (distance wp2 wp3) 7)
    (= (distance wp3 wp2) 7)
    (= (distance wp2 printer0) 14)
    (= (distance printer0 wp2) 14)
    (= (distance wp2 printer1) 19)
    (= (distance printer1 wp2) 19)
    (= (distance wp2 printer2) 11)
    (= (distance printer2 wp2) 11)
    (= (distance wp3 printer0) 21)
    (= (distance printer0 wp3) 21)
    (= (distance wp3 printer1) 18)
    (= (distance printer1 wp3) 18)
    (= (distance wp3 printer2) 10)
    (= (distance printer2 wp3) 10)
    (= (distance printer0 printer1) 17)
    (= (distance printer1 printer0) 17)
    (= (distance printer0 printer2) 13)
    (= (distance printer2 printer0) 13)
    (= (distance printer1 printer2) 8)
    (= (distance printer2 printer1) 8)
)
(:goal (and
    (papers_delivered wp0)
    (papers_delivered wp1)
    (papers_delivered wp2)
))
)
