(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 wp4 wp5 - waypoint
    printer0 printer1 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp1)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp4)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0) (at 660.004 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 660.004 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 660.004 (not (delivery_destination wp2)))
    (delivery_destination wp3) (at 660.004 (not (delivery_destination wp3)))
    (delivery_destination wp4) (at 660.004 (not (delivery_destination wp4)))
    (delivery_destination wp5) (at 660.004 (not (delivery_destination wp5)))

    (= (distance wp0 wp1) 10)
    (= (distance wp1 wp0) 10)
    (= (distance wp0 wp2) 4)
    (= (distance wp2 wp0) 4)
    (= (distance wp0 wp3) 18)
    (= (distance wp3 wp0) 18)
    (= (distance wp0 wp4) 6)
    (= (distance wp4 wp0) 6)
    (= (distance wp0 wp5) 11)
    (= (distance wp5 wp0) 11)
    (= (distance wp0 printer0) 7)
    (= (distance printer0 wp0) 7)
    (= (distance wp0 printer1) 8)
    (= (distance printer1 wp0) 8)
    (= (distance wp1 wp2) 14)
    (= (distance wp2 wp1) 14)
    (= (distance wp1 wp3) 8)
    (= (distance wp3 wp1) 8)
    (= (distance wp1 wp4) 12)
    (= (distance wp4 wp1) 12)
    (= (distance wp1 wp5) 15)
    (= (distance wp5 wp1) 15)
    (= (distance wp1 printer0) 5)
    (= (distance printer0 wp1) 5)
    (= (distance wp1 printer1) 8)
    (= (distance printer1 wp1) 8)
    (= (distance wp2 wp3) 22)
    (= (distance wp3 wp2) 22)
    (= (distance wp2 wp4) 2)
    (= (distance wp4 wp2) 2)
    (= (distance wp2 wp5) 7)
    (= (distance wp5 wp2) 7)
    (= (distance wp2 printer0) 11)
    (= (distance printer0 wp2) 11)
    (= (distance wp2 printer1) 12)
    (= (distance printer1 wp2) 12)
    (= (distance wp3 wp4) 20)
    (= (distance wp4 wp3) 20)
    (= (distance wp3 wp5) 23)
    (= (distance wp5 wp3) 23)
    (= (distance wp3 printer0) 11)
    (= (distance printer0 wp3) 11)
    (= (distance wp3 printer1) 12)
    (= (distance printer1 wp3) 12)
    (= (distance wp4 wp5) 5)
    (= (distance wp5 wp4) 5)
    (= (distance wp4 printer0) 9)
    (= (distance printer0 wp4) 9)
    (= (distance wp4 printer1) 12)
    (= (distance printer1 wp4) 12)
    (= (distance wp5 printer0) 12)
    (= (distance printer0 wp5) 12)
    (= (distance wp5 printer1) 17)
    (= (distance printer1 wp5) 17)
    (= (distance printer0 printer1) 13)
    (= (distance printer1 printer0) 13)
)
(:goal (and
    (papers_delivered wp1)
    (papers_delivered wp0)
    (papers_delivered wp4)
))
)
