(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp2)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp3)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp1)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0) (at 4920.006 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 4920.006 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 4920.006 (not (delivery_destination wp2)))
    (delivery_destination wp3) (at 4920.006 (not (delivery_destination wp3)))

    (= (distance wp0 wp1) 80)
    (= (distance wp1 wp0) 80)
    (= (distance wp0 wp2) 83)
    (= (distance wp2 wp0) 83)
    (= (distance wp0 wp3) 31)
    (= (distance wp3 wp0) 31)
    (= (distance wp0 printer0) 57)
    (= (distance printer0 wp0) 57)
    (= (distance wp0 printer1) 27)
    (= (distance printer1 wp0) 27)
    (= (distance wp1 wp2) 3)
    (= (distance wp2 wp1) 3)
    (= (distance wp1 wp3) 93)
    (= (distance wp3 wp1) 93)
    (= (distance wp1 printer0) 137)
    (= (distance printer0 wp1) 137)
    (= (distance wp1 printer1) 53)
    (= (distance printer1 wp1) 53)
    (= (distance wp2 wp3) 96)
    (= (distance wp3 wp2) 96)
    (= (distance wp2 printer0) 140)
    (= (distance printer0 wp2) 140)
    (= (distance wp2 printer1) 56)
    (= (distance printer1 wp2) 56)
    (= (distance wp3 printer0) 44)
    (= (distance printer0 wp3) 44)
    (= (distance wp3 printer1) 40)
    (= (distance printer1 wp3) 40)
    (= (distance printer0 printer1) 84)
    (= (distance printer1 printer0) 84)
)
(:goal (and
    (papers_delivered wp2)
    (papers_delivered wp3)
    (papers_delivered wp1)
))
)
