(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 - waypoint
    printer0 printer1 printer2 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp2)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp1)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0) (at 1275.006 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 1275.006 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 1275.006 (not (delivery_destination wp2)))

    (= (distance wp0 wp1) 40)
    (= (distance wp1 wp0) 40)
    (= (distance wp0 wp2) 18)
    (= (distance wp2 wp0) 18)
    (= (distance wp0 printer0) 21)
    (= (distance printer0 wp0) 21)
    (= (distance wp0 printer1) 50)
    (= (distance printer1 wp0) 50)
    (= (distance wp0 printer2) 103)
    (= (distance printer2 wp0) 103)
    (= (distance wp1 wp2) 52)
    (= (distance wp2 wp1) 52)
    (= (distance wp1 printer0) 47)
    (= (distance printer0 wp1) 47)
    (= (distance wp1 printer1) 10)
    (= (distance printer1 wp1) 10)
    (= (distance wp1 printer2) 63)
    (= (distance printer2 wp1) 63)
    (= (distance wp2 printer0) 39)
    (= (distance printer0 wp2) 39)
    (= (distance wp2 printer1) 62)
    (= (distance printer1 wp2) 62)
    (= (distance wp2 printer2) 115)
    (= (distance printer2 wp2) 115)
    (= (distance printer0 printer1) 53)
    (= (distance printer1 printer0) 53)
    (= (distance printer0 printer2) 96)
    (= (distance printer2 printer0) 96)
    (= (distance printer1 printer2) 53)
    (= (distance printer2 printer1) 53)
)
(:goal (and
    (papers_delivered wp2)
    (papers_delivered wp1)
))
)
