(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 - waypoint
    printer0 printer1 printer2 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp2)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp1)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0) (at 1920.0045 (not (delivery_destination wp0)))
    (delivery_destination wp1) (at 1920.0045 (not (delivery_destination wp1)))
    (delivery_destination wp2) (at 1920.0045 (not (delivery_destination wp2)))

    (= (distance wp0 wp1) 100)
    (= (distance wp1 wp0) 100)
    (= (distance wp0 wp2) 6)
    (= (distance wp2 wp0) 6)
    (= (distance wp0 printer0) 30)
    (= (distance printer0 wp0) 30)
    (= (distance wp0 printer1) 89)
    (= (distance printer1 wp0) 89)
    (= (distance wp0 printer2) 22)
    (= (distance printer2 wp0) 22)
    (= (distance wp1 wp2) 100)
    (= (distance wp2 wp1) 100)
    (= (distance wp1 printer0) 70)
    (= (distance printer0 wp1) 70)
    (= (distance wp1 printer1) 17)
    (= (distance printer1 wp1) 17)
    (= (distance wp1 printer2) 78)
    (= (distance printer2 wp1) 78)
    (= (distance wp2 printer0) 30)
    (= (distance printer0 wp2) 30)
    (= (distance wp2 printer1) 89)
    (= (distance printer1 wp2) 89)
    (= (distance wp2 printer2) 22)
    (= (distance printer2 wp2) 22)
    (= (distance printer0 printer1) 59)
    (= (distance printer1 printer0) 59)
    (= (distance printer0 printer2) 26)
    (= (distance printer2 printer0) 26)
    (= (distance printer1 printer2) 67)
    (= (distance printer2 printer1) 67)
)
(:goal (and
    (papers_delivered wp2)
    (papers_delivered wp0)
    (papers_delivered wp1)
))
)
