(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 printer3 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 85)
    (= (distance wp1 wp0) 85)
    (= (distance wp0 wp2) 24)
    (= (distance wp2 wp0) 24)
    (= (distance wp0 wp3) 13)
    (= (distance wp3 wp0) 13)
    (= (distance wp0 printer0) 33)
    (= (distance printer0 wp0) 33)
    (= (distance wp0 printer1) 18)
    (= (distance printer1 wp0) 18)
    (= (distance wp0 printer2) 82)
    (= (distance printer2 wp0) 82)
    (= (distance wp0 printer3) 65)
    (= (distance printer3 wp0) 65)
    (= (distance wp1 wp2) 83)
    (= (distance wp2 wp1) 83)
    (= (distance wp1 wp3) 98)
    (= (distance wp3 wp1) 98)
    (= (distance wp1 printer0) 72)
    (= (distance printer0 wp1) 72)
    (= (distance wp1 printer1) 67)
    (= (distance printer1 wp1) 67)
    (= (distance wp1 printer2) 83)
    (= (distance printer2 wp1) 83)
    (= (distance wp1 printer3) 44)
    (= (distance printer3 wp1) 44)
    (= (distance wp2 wp3) 37)
    (= (distance wp3 wp2) 37)
    (= (distance wp2 printer0) 53)
    (= (distance printer0 wp2) 53)
    (= (distance wp2 printer1) 26)
    (= (distance printer1 wp2) 26)
    (= (distance wp2 printer2) 58)
    (= (distance printer2 wp2) 58)
    (= (distance wp2 printer3) 41)
    (= (distance printer3 wp2) 41)
    (= (distance wp3 printer0) 26)
    (= (distance printer0 wp3) 26)
    (= (distance wp3 printer1) 31)
    (= (distance printer1 wp3) 31)
    (= (distance wp3 printer2) 95)
    (= (distance printer2 wp3) 95)
    (= (distance wp3 printer3) 78)
    (= (distance printer3 wp3) 78)
    (= (distance printer0 printer1) 27)
    (= (distance printer1 printer0) 27)
    (= (distance printer0 printer2) 69)
    (= (distance printer2 printer0) 69)
    (= (distance printer0 printer3) 52)
    (= (distance printer3 printer0) 52)
    (= (distance printer1 printer2) 64)
    (= (distance printer2 printer1) 64)
    (= (distance printer1 printer3) 47)
    (= (distance printer3 printer1) 47)
    (= (distance printer2 printer3) 39)
    (= (distance printer3 printer2) 39)
)
(:goal (and
    (papers_delivered wp2)
    (papers_delivered wp1)
    (papers_delivered wp1)
    (papers_delivered wp0)
    (papers_delivered wp0)
    (papers_delivered wp3)
    (papers_delivered wp3)
    (papers_delivered wp2)
))
)
