(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 printer3 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 36)
    (= (distance wp1 wp0) 36)
    (= (distance wp0 wp2) 53)
    (= (distance wp2 wp0) 53)
    (= (distance wp0 wp3) 109)
    (= (distance wp3 wp0) 109)
    (= (distance wp0 printer0) 20)
    (= (distance printer0 wp0) 20)
    (= (distance wp0 printer1) 66)
    (= (distance printer1 wp0) 66)
    (= (distance wp0 printer2) 47)
    (= (distance printer2 wp0) 47)
    (= (distance wp0 printer3) 100)
    (= (distance printer3 wp0) 100)
    (= (distance wp1 wp2) 17)
    (= (distance wp2 wp1) 17)
    (= (distance wp1 wp3) 73)
    (= (distance wp3 wp1) 73)
    (= (distance wp1 printer0) 16)
    (= (distance printer0 wp1) 16)
    (= (distance wp1 printer1) 96)
    (= (distance printer1 wp1) 96)
    (= (distance wp1 printer2) 83)
    (= (distance printer2 wp1) 83)
    (= (distance wp1 printer3) 64)
    (= (distance printer3 wp1) 64)
    (= (distance wp2 wp3) 56)
    (= (distance wp3 wp2) 56)
    (= (distance wp2 printer0) 33)
    (= (distance printer0 wp2) 33)
    (= (distance wp2 printer1) 113)
    (= (distance printer1 wp2) 113)
    (= (distance wp2 printer2) 100)
    (= (distance printer2 wp2) 100)
    (= (distance wp2 printer3) 55)
    (= (distance printer3 wp2) 55)
    (= (distance wp3 printer0) 89)
    (= (distance printer0 wp3) 89)
    (= (distance wp3 printer1) 81)
    (= (distance printer1 wp3) 81)
    (= (distance wp3 printer2) 156)
    (= (distance printer2 wp3) 156)
    (= (distance wp3 printer3) 23)
    (= (distance printer3 wp3) 23)
    (= (distance printer0 printer1) 80)
    (= (distance printer1 printer0) 80)
    (= (distance printer0 printer2) 67)
    (= (distance printer2 printer0) 67)
    (= (distance printer0 printer3) 80)
    (= (distance printer3 printer0) 80)
    (= (distance printer1 printer2) 107)
    (= (distance printer2 printer1) 107)
    (= (distance printer1 printer3) 58)
    (= (distance printer3 printer1) 58)
    (= (distance printer2 printer3) 147)
    (= (distance printer3 printer2) 147)
)
(:goal (and
    (papers_delivered wp0)
    (papers_delivered wp2)
    (papers_delivered wp3)
    (papers_delivered wp1)
    (papers_delivered wp0)
    (papers_delivered wp1)
    (papers_delivered wp2)
    (papers_delivered wp1)
    (papers_delivered wp1)
))
)
