(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 wp4 - waypoint
    robot0 robot1 robot2 - robot
    printer0 printer1 printer2 printer3 - printer
)
(:init
    (robot_at robot0 wp0)
    (robot_at robot1 wp0)
    (robot_at robot2 wp0)

    (undocked robot0)
    (undocked robot1)
    (undocked robot2)


    (localised robot0)
    (localised robot1)
    (localised robot2)

    (dock_at wp0)


    (nocarrying_papers robot0)
    (nocarrying_papers robot1)
    (nocarrying_papers robot2)



    (delivery_destination wp0)
    (at 2194.25 (not (delivery_destination wp0)))
    (delivery_destination wp1)
    (at 2194.25 (not (delivery_destination wp1)))
    (delivery_destination wp2)
    (at 2194.25 (not (delivery_destination wp2)))
    (delivery_destination wp3)
    (at 2194.25 (not (delivery_destination wp3)))
    (delivery_destination wp4)
    (at 2194.25 (not (delivery_destination wp4)))

    (= (distance wp0 wp1) 42)
    (= (distance wp1 wp0) 42)
    (= (distance wp0 wp2) 54)
    (= (distance wp2 wp0) 54)
    (= (distance wp0 wp3) 57)
    (= (distance wp3 wp0) 57)
    (= (distance wp0 wp4) 40)
    (= (distance wp4 wp0) 40)
    (= (distance wp0 printer0) 64)
    (= (distance printer0 wp0) 64)
    (= (distance wp0 printer1) 26)
    (= (distance printer1 wp0) 26)
    (= (distance wp0 printer2) 26)
    (= (distance printer2 wp0) 26)
    (= (distance wp0 printer3) 30)
    (= (distance printer3 wp0) 30)
    (= (distance wp1 wp2) 80)
    (= (distance wp2 wp1) 80)
    (= (distance wp1 wp3) 99)
    (= (distance wp3 wp1) 99)
    (= (distance wp1 wp4) 66)
    (= (distance wp4 wp1) 66)
    (= (distance wp1 printer0) 106)
    (= (distance printer0 wp1) 106)
    (= (distance wp1 printer1) 52)
    (= (distance printer1 wp1) 52)
    (= (distance wp1 printer2) 52)
    (= (distance printer2 wp1) 52)
    (= (distance wp1 printer3) 20)
    (= (distance printer3 wp1) 20)
    (= (distance wp2 wp3) 53)
    (= (distance wp3 wp2) 53)
    (= (distance wp2 wp4) 14)
    (= (distance wp4 wp2) 14)
    (= (distance wp2 printer0) 60)
    (= (distance printer0 wp2) 60)
    (= (distance wp2 printer1) 28)
    (= (distance printer1 wp2) 28)
    (= (distance wp2 printer2) 28)
    (= (distance printer2 wp2) 28)
    (= (distance wp2 printer3) 60)
    (= (distance printer3 wp2) 60)
    (= (distance wp3 wp4) 51)
    (= (distance wp4 wp3) 51)
    (= (distance wp3 printer0) 23)
    (= (distance printer0 wp3) 23)
    (= (distance wp3 printer1) 73)
    (= (distance printer1 wp3) 73)
    (= (distance wp3 printer2) 67)
    (= (distance printer2 wp3) 67)
    (= (distance wp3 printer3) 87)
    (= (distance printer3 wp3) 87)
    (= (distance wp4 printer0) 58)
    (= (distance printer0 wp4) 58)
    (= (distance wp4 printer1) 22)
    (= (distance printer1 wp4) 22)
    (= (distance wp4 printer2) 16)
    (= (distance printer2 wp4) 16)
    (= (distance wp4 printer3) 46)
    (= (distance printer3 wp4) 46)
    (= (distance printer0 printer1) 80)
    (= (distance printer1 printer0) 80)
    (= (distance printer0 printer2) 74)
    (= (distance printer2 printer0) 74)
    (= (distance printer0 printer3) 94)
    (= (distance printer3 printer0) 94)
    (= (distance printer1 printer2) 6)
    (= (distance printer2 printer1) 6)
    (= (distance printer1 printer3) 32)
    (= (distance printer3 printer1) 32)
    (= (distance printer2 printer3) 32)
    (= (distance printer3 printer2) 32)

)
(:goal (and
    (papers_delivered wp0)
    (papers_delivered wp3)
    (papers_delivered wp4)
    (papers_delivered wp0)
    (papers_delivered wp1)
    (papers_delivered wp2)
    (papers_delivered wp3)
    (papers_delivered wp3)
    (papers_delivered wp0)
    (papers_delivered wp3)
))
)
