(define (problem task)
(:domain turtlebot)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    printer0 printer1 printer2 printer3 - printer
    robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_papers robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_papers robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_papers robot2)
    (undocked robot2)
    (localised robot2)

    (dock_at wp0)

    (delivery_destination wp0)
    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp3)

    (= (distance wp0 wp1) 57)
    (= (distance wp1 wp0) 57)
    (= (distance wp0 wp2) 34)
    (= (distance wp2 wp0) 34)
    (= (distance wp0 wp3) 41)
    (= (distance wp3 wp0) 41)
    (= (distance wp0 printer0) 51)
    (= (distance printer0 wp0) 51)
    (= (distance wp0 printer1) 65)
    (= (distance printer1 wp0) 65)
    (= (distance wp0 printer2) 101)
    (= (distance printer2 wp0) 101)
    (= (distance wp0 printer3) 61)
    (= (distance printer3 wp0) 61)
    (= (distance wp1 wp2) 31)
    (= (distance wp2 wp1) 31)
    (= (distance wp1 wp3) 50)
    (= (distance wp3 wp1) 50)
    (= (distance wp1 printer0) 48)
    (= (distance printer0 wp1) 48)
    (= (distance wp1 printer1) 68)
    (= (distance printer1 wp1) 68)
    (= (distance wp1 printer2) 50)
    (= (distance printer2 wp1) 50)
    (= (distance wp1 printer3) 24)
    (= (distance printer3 wp1) 24)
    (= (distance wp2 wp3) 75)
    (= (distance wp3 wp2) 75)
    (= (distance wp2 printer0) 17)
    (= (distance printer0 wp2) 17)
    (= (distance wp2 printer1) 99)
    (= (distance printer1 wp2) 99)
    (= (distance wp2 printer2) 75)
    (= (distance printer2 wp2) 75)
    (= (distance wp2 printer3) 35)
    (= (distance printer3 wp2) 35)
    (= (distance wp3 printer0) 92)
    (= (distance printer0 wp3) 92)
    (= (distance wp3 printer1) 44)
    (= (distance printer1 wp3) 44)
    (= (distance wp3 printer2) 94)
    (= (distance printer2 wp3) 94)
    (= (distance wp3 printer3) 68)
    (= (distance printer3 wp3) 68)
    (= (distance printer0 printer1) 116)
    (= (distance printer1 printer0) 116)
    (= (distance printer0 printer2) 92)
    (= (distance printer2 printer0) 92)
    (= (distance printer0 printer3) 52)
    (= (distance printer3 printer0) 52)
    (= (distance printer1 printer2) 118)
    (= (distance printer2 printer1) 118)
    (= (distance printer1 printer3) 92)
    (= (distance printer3 printer1) 92)
    (= (distance printer2 printer3) 40)
    (= (distance printer3 printer2) 40)
)
(:goal (and
    (papers_delivered wp1)
    (papers_delivered wp3)
    (papers_delivered wp2)
))
)
